version: "2"

run:
  timeout: 5m
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/skosovsky/toolsy

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
  gosec:
    severity: medium
    confidence: medium

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocritic
    - revive
    - gosec
    - testifylint
    - unconvert
    - sloglint

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    - path: '(.+)_test\.go$'
      linters:
        - errcheck
        - gosec
        - revive
    - path: vendor/
      text: ".*"
