.PHONY: test lint bench fuzz cover test-all lint-all fix-all

# test runs root + all nested modules (no false green without toolkits).
test:
	@go test -race -count=1 ./...
	@cd mcp && go test -race -count=1 ./...
	@cd agents && go test -race -count=1 ./...
	@cd toolkits/memory && go test -race -count=1 ./...
	@cd toolkits/rag && go test -race -count=1 ./...
	@cd toolkits/prompts && go test -race -count=1 ./...
	@cd toolkits/human && go test -race -count=1 ./...
	@cd toolkits/httptool && go test -race -count=1 ./...
	@cd toolkits/fstool && go test -race -count=1 ./...
	@cd toolkits/sqltool && go test -race -count=1 ./...
	@cd toolkits/document && go test -race -count=1 ./...
	@cd toolkits/web && go test -race -count=1 ./...
	@cd toolkits/exectool && go test -race -count=1 ./...
	@cd toolkits/timetool && go test -race -count=1 ./...
	@cd toolkits/mail && go test -race -count=1 ./...

test-all: test

# lint runs root + all nested modules.
lint:
	@golangci-lint run ./...
	@cd mcp && golangci-lint run ./...
	@cd agents && golangci-lint run ./...
	@cd toolkits/memory && golangci-lint run ./...
	@cd toolkits/rag && golangci-lint run ./...
	@cd toolkits/prompts && golangci-lint run ./...
	@cd toolkits/human && golangci-lint run ./...
	@cd toolkits/httptool && golangci-lint run ./...
	@cd toolkits/fstool && golangci-lint run ./...
	@cd toolkits/sqltool && golangci-lint run ./...
	@cd toolkits/document && golangci-lint run ./...
	@cd toolkits/web && golangci-lint run ./...
	@cd toolkits/exectool && golangci-lint run ./...
	@cd toolkits/timetool && golangci-lint run ./...
	@cd toolkits/mail && golangci-lint run ./...

lint-all: lint
	@cd contracts/openapi && golangci-lint run ./...
	@cd contracts/graphql && golangci-lint run ./...
	@cd contracts/grpc && golangci-lint run ./...

fix-all:
	@go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd mcp && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd agents && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd contracts/openapi && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd contracts/graphql && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd contracts/grpc && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/memory && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/rag && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/prompts && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/human && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/httptool && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/fstool && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/sqltool && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/document && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/web && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/exectool && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/timetool && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd toolkits/mail && go mod tidy && go fix ./... && golangci-lint run --fix ./...

bench:
	@go test -bench=. -benchmem ./...

fuzz:
	@go test -fuzz=. -fuzztime=30s .

cover:
	@go test -coverprofile=coverage.out -covermode=atomic ./...
	@go tool cover -func=coverage.out
