.PHONY: test lint bench fuzz cover test-all lint-all fix-all

test:
	@go test -race -count=1 ./...

test-all: test
	@cd mcp && go test -race -count=1 ./...
	@cd agents && go test -race -count=1 ./...

lint:
	@golangci-lint run ./...

lint-all: lint
	@cd mcp && golangci-lint run ./...
	@cd agents && golangci-lint run ./...
	@cd contracts/openapi && golangci-lint run ./...
	@cd contracts/graphql && golangci-lint run ./...
	@cd contracts/grpc && golangci-lint run ./...

fix-all:
	@go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd mcp && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd agents && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd contracts/openapi && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd contracts/graphql && go mod tidy && go fix ./... && golangci-lint run --fix ./...
	@cd contracts/grpc && go mod tidy && go fix ./... && golangci-lint run --fix ./...

bench:
	@go test -bench=. -benchmem ./...

fuzz:
	@go test -fuzz=. -fuzztime=30s .

cover:
	@go test -coverprofile=coverage.out -covermode=atomic ./...
	@go tool cover -func=coverage.out
