.PHONY: test lint bench fuzz cover test-all lint-all

test:
	@go test -race -count=1 ./...

test-all: test
	@cd mcp && go test -race -count=1 ./...
	@cd agents && go test -race -count=1 ./...

lint:
	@golangci-lint run ./...

lint-all: lint
	@cd mcp && golangci-lint run ./...
	@cd agents && golangci-lint run ./...

bench:
	@go test -bench=. -benchmem ./...

fuzz:
	@go test -fuzz=. -fuzztime=30s .

cover:
	@go test -coverprofile=coverage.out -covermode=atomic ./...
	@go tool cover -func=coverage.out
