// Code generated by toolsy-gen. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"github.com/skosovsky/toolsy"
	"iter"
)

// ProgressInput is the decoded input for the "progress" tool.
type ProgressInput struct {
	RawJSON json.RawMessage `json:"-"`
	Count   *json.Number    `json:"count"`
}

// ProgressStreamHandler executes the "progress" tool in streaming mode.
type ProgressStreamHandler interface {
	ExecuteStream(ctx context.Context, input ProgressInput) iter.Seq2[string, error]
}

// NewProgressTool builds the "progress" tool.
func NewProgressTool(handler ProgressStreamHandler) (toolsy.Tool, error) {
	if handler == nil {
		return nil, errors.New("progressstreamhandler must not be nil")
	}
	const rawSchema = "{\"properties\":{\"count\":{\"description\":\"Number of parts to emit\",\"maximum\":10,\"minimum\":1,\"type\":\"integer\"}},\"required\":[\"count\"],\"type\":\"object\"}"

	proxy, err := toolsy.NewProxyTool("progress", "Emit progress parts synchronously or through explicit host async composition", []byte(rawSchema), func(ctx context.Context, _ *toolsy.RunEnv, rawArgs []byte, yield func(toolsy.Chunk) error) error {
		var original map[string]json.RawMessage
		if err := json.Unmarshal(rawArgs, &original); err != nil {
			return toolsy.NewSchemaError("invalid JSON object")
		}
		declared := make(map[string]json.RawMessage)
		if value, present := original["count"]; present {
			declared["count"] = value
		}
		decoded, err := json.Marshal(declared)
		if err != nil {
			return err
		}
		var input ProgressInput
		if err := json.Unmarshal(decoded, &input); err != nil {
			return toolsy.NewSchemaError("Validation failed: invalid JSON format or type mismatch")
		}
		input.RawJSON = append(json.RawMessage(nil), rawArgs...)
		var pending string
		havePending := false
		for part, err := range handler.ExecuteStream(ctx, input) {
			if interrupt := ctx.Err(); interrupt != nil {
				return interrupt
			}
			if err != nil {
				if havePending {
					if err := yield(toolsy.Chunk{Event: toolsy.EventProgress, Data: []byte(pending), MimeType: toolsy.MimeTypeText}); err != nil {
						return err
					}
				}
				return err
			}
			if havePending {
				if err := yield(toolsy.Chunk{Event: toolsy.EventProgress, Data: []byte(pending), MimeType: toolsy.MimeTypeText}); err != nil {
					return err
				}
			}
			pending = part
			havePending = true
		}
		if interrupt := ctx.Err(); interrupt != nil {
			return interrupt
		}
		if !havePending {
			return yield(toolsy.Chunk{Event: toolsy.EventResult})
		}
		return yield(toolsy.Chunk{
			Event:    toolsy.EventResult,
			Data:     []byte(pending),
			MimeType: toolsy.MimeTypeText,
		})
	})
	if err != nil {
		return nil, err
	}
	return proxy, nil
}
