package agents

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"unicode/utf8"

	"github.com/skosovsky/toolsy/internal/jsonschemax"
)

const (
	schemaTypeKey = "type"
	taskIDKey     = "task_id"
	artifactsKey  = "artifacts"
)

// Task projects the creation envelope from the supported Agent Protocol subset.
type Task struct {
	TaskID    string     `json:"task_id"`
	Input     *string    `json:"input"` // Optional normative string/null input; BYO arguments use additional_input.
	Artifacts []Artifact `json:"artifacts"`
}

// Artifact represents a file or data generated by the agent (multimodal output).
type Artifact struct {
	ArtifactID string `json:"artifact_id"`
	FileName   string `json:"file_name"`
	MimeType   string `json:"mime_type,omitempty"` // e.g. "image/png"
	Data       string `json:"data,omitempty"`      // Base64 when server includes inline data
}

// Step represents one step of the agent's internal execution (streamed via SSE).
type Step struct {
	StepID    string     `json:"step_id"`
	TaskID    string     `json:"task_id"`
	Name      string     `json:"name"`
	Status    string     `json:"status"` // created/running/completed; extension terminal failed/cancelled.
	IsLast    bool       `json:"is_last"`
	Output    string     `json:"output,omitempty"`
	Artifacts []Artifact `json:"artifacts,omitempty"`
}

// createTaskRequest maps BYO object arguments into normative additional_input.
type createTaskRequest struct {
	AdditionalInput json.RawMessage `json:"additional_input"`
}

// UnmarshalJSON validates the required fields of the pinned v1 Step envelope.
// Extension statuses are checked separately so protocol failures remain typed outcomes.
func (s *Step) UnmarshalJSON(data []byte) error {
	type wire Step
	fields, err := envelopeFields(
		data,
		[]string{"step_id", taskIDKey, "name", "status", "is_last", "output", artifactsKey},
	)
	if err != nil {
		return err
	}
	for _, key := range []string{"step_id", taskIDKey, "status", "is_last", artifactsKey} {
		value, exists := fields[key]
		if !exists || string(value) == "null" {
			return fmt.Errorf("agents: missing required step field %s", key)
		}
	}
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*s = Step(decoded)
	return nil
}

// UnmarshalJSON prevents case-insensitive aliases from changing task references.
func (t *Task) UnmarshalJSON(data []byte) error {
	type wire Task
	if _, err := envelopeFields(data, []string{taskIDKey, "input", artifactsKey}); err != nil {
		return err
	}
	var decoded wire
	err := json.Unmarshal(data, &decoded)
	*t = Task(decoded)
	return err
}

func envelopeFields(data []byte, names []string) (map[string]json.RawMessage, error) {
	if !utf8.Valid(data) {
		return nil, errors.New("agents: invalid UTF-8 envelope")
	}
	if _, err := jsonschemax.Decode(data); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return nil, err
	}
	if fields == nil {
		return nil, errors.New("agents: envelope must be an object")
	}
	for key := range fields {
		for _, name := range names {
			if key != name && strings.EqualFold(key, name) {
				return nil, errors.New("agents: noncanonical envelope field")
			}
		}
	}
	return fields, nil
}
