package agents

import "encoding/json"

// Task represents a task assigned to the agent (Agent Protocol).
type Task struct {
	TaskID string          `json:"task_id"`
	Input  json.RawMessage `json:"input"`  // Dynamic JSON from the orchestrator
	Status string          `json:"status"` // "created", "running", "completed", "failed"
}

// Artifact represents a file or data generated by the agent (multimodal output).
type Artifact struct {
	ArtifactID string `json:"artifact_id"`
	FileName   string `json:"file_name"`
	MimeType   string `json:"mime_type,omitempty"` // e.g. "image/png"
	Data       string `json:"data,omitempty"`      // Base64 when server includes inline data
}

// Step represents one step of the agent's internal execution (streamed via SSE).
type Step struct {
	StepID    string     `json:"step_id"`
	TaskID    string     `json:"task_id"`
	Name      string     `json:"name"`
	Status    string     `json:"status"` // "running", "completed", "failed"
	IsLast    bool       `json:"is_last"`
	Output    string     `json:"output,omitempty"`
	Artifacts []Artifact `json:"artifacts,omitempty"`
}

// createTaskRequest is the request body for POST /ap/v1/agent/tasks (Agent Protocol).
type createTaskRequest struct {
	Input json.RawMessage `json:"input"`
}

// createTaskResponse wraps the task in API response if the server returns {"task": {...}}.
type createTaskResponse struct {
	Task *Task `json:"task"`
}
